### ISSUE TITLE
Feature Request: integrating Traffic and Weather Maps

### ISSUE THREAD

**Issue by mjb32803** [cmnybo/nrsc5-gui#2]
I'm currently trying nrsc5-gui on a stand-alone Raspberry Pi 3 B+ as my work desk radio.  I also often use the hdfm.py program from  KYDronePilot/hdfm to check out traffic and weather maps.  Switching back and forth is do-able, but integrating the two together would be awesomeness.  Incorporating the two maps as additional tabs, similar to the Album Art tab.

**Comment by cmnybo** [comment]
I have added support for weather radar and traffic maps. I have pushed it to the experimental branch.
Please let me know if everything is working correctly, then I will merge it with the master branch.

The new version requires a couple more dependencies. It uses PIL to process images and NumPy to convert PIL images to image arrays that GTK can use.

**Comment by mjb32803** [comment]
I had a small issue where I was missing the python-dateutil dependency.
Not sure why that specific piece was missing, but when I manually installed, everything ran just fine.

**Comment by cmnybo** [comment]
I added python-dateutil to the list of dependencies in the readme and merged the branch to master.
