### ISSUE TITLE
rtl_tcp support

### ISSUE THREAD

**Issue by NSBrianWard** [cmnybo/nrsc5-gui#23]
So I typically have my SDR attached to a remote Raspberry Pi, and then I connect to that so I can listen to things over the network. Does the GUI support this setup? I typically do the following from the command line:

On my raspberrypi: `sudo rtl_tcp -a 10.0.3.72` <-- starting the radio server
Then from my computer: `nrsc5 -H 10.0.3.72:1234 94.9 0` <-- connecting to it so I can listen to a station

I see a place to put in a number for the device assuming it's connected locally, but not a specific way to point it at an IP address. Any ideas? Thanks!

**Comment by NSBrianWard** [comment]
Looking into this a little further, I see on line `477` of `nrsc5.py` an `open_rtltcp()` function. I'm guessing maybe this just isn't hooked up to the UI yet?

**Comment by NSBrianWard** [comment]
Aha! If I just comment out line `396` of `nrsc5_gui.py` and use `self.radio.open_rtltcp("10.0.3.72", "1234")` instead it will work without issue.

**Comment by markjfine** [comment]
I nrsc5-dui has the interface for rtltcp.

**Comment by NSBrianWard** [comment]
I got it to do the thing! 😉

![Screen Shot 2022-10-02 at 2 25 28 PM](https://user-images.githubusercontent.com/1589831/193476957-6ffdcce7-31f8-44bb-9099-d9b1a1c6e305.png)

![Screen Shot 2022-10-02 at 2 25 35 PM](https://user-images.githubusercontent.com/1589831/193476964-ab177c00-0c2e-4d12-b00a-7cae1e27698d.png)
