### ISSUE TITLE
Previous Stream "Sticking" After Change

### ISSUE THREAD

**Issue by TripEricson** [cmnybo/nrsc5-gui#5]
I'm not sure this is a bug so much as an odd behavior, which may be inherent to Gtk or something.  For example, I'm tuned to an HD1 right now.  If I hit Stop, then replace the Stream ID with a "2", then immediately hit Play, it tunes back into the HD1.  Now, if I hit Stop again, then without touching anything, hit Play, now I'm tuned to HD2.  

It appears that what's happening is that although I've replaced the text, because I've not hit Tab or Enter before hitting Play, it's not registering that I've changed it to a HD2 until I hit Stop again.  Then, when I again hit Play, it properly registers.

I'm not sure this is worth fixing or fixable at all, but thought I would flag it in case someone else runs into it.  It took me a day or two to figure out why it kept "sticking" like that.

**Comment by cmnybo** [comment]
I think that's just how the GTK spin buttons works.
If you type in a number and don't press enter or go to another input, the new value will not be applied.

I just changed version 1.1.1 to force update all of the spin buttons when play is clicked. This should fix the issue with them sticking.

**Comment by TripEricson** [comment]
It appears to be better now; thanks so much.  Your UI makes NRSC5 much more usable.

I'm also going to separately file a ticket for a question and a handful of potential enhancements.
