### ISSUE TITLE
Audio starts but no data is read

### ISSUE THREAD

**Issue by lmore377** [cmnybo/nrsc5-gui#8]
When I start a station it will play the audio and images are downladed into aas but there's no song info, album art dosen't show, and no maps work. I'm running this on Ubuntu 18.10

**Comment by lmore377** [comment]
I got the station/track info working by editing the regex part a bit.
`        # regex for getting nrsc5 output
        self.regex = [
            re.compile("^.*main\.c:[\d]+: Station name: (.*)$"),                                                    #  0 match Callsign
            re.compile("^.*main\.c:[\d]+: Station location: (-?[\d]+\.[\d]+) (-?[\d]+\.[\d]+), ([\d]+)m$"),         #  1 match station location
            re.compile("^.*main\.c:[\d]+: Slogan: (.*)$"),                                                          #  2 match station slogan
            re.compile("^.*main\.c:[\d]+: Audio bit rate: (.*) kbps$"),                                           #  3 match audio bit rate
            re.compile("^.*main\.c:[\d]+: Title: (.*)$"),                                                         #  4 match title
            re.compile("^.*main\.c:[\d]+: Artist: (.*)$"),                                                        #  5 match artist
            re.compile("^.*main\.c:[\d]+: Album: (.*)$"),                                                         #  6 match album
            re.compile("^.*output\.c:[\d]+: File (.*\.(?:jpg|png|txt)), port ([0-9a-fA-F]+).*$"),               #  7 match file (album art, maps, weather info)
            re.compile("^.*main\.c:[\d]+: MER: (-?[\d]+\.[\d]+) dB \(lower\), (-?[\d]+\.[\d]+) dB \(upper\)$"),     #  8 match MER
            re.compile("^.*main\.c:[\d]+: BER: (0\.[\d]+), avg: (0\.[\d]+), min: (0\.[\d]+), max: (0\.[\d]+)$"),  #  9 match BER
            re.compile("^.*nrsc5\.c:[\d]+: Best gain: (.*)$"),                                                       # 10 match gain
            re.compile("^.*output\.c:[\d]+: ([0-9a-fA-F]{2}) ([0-9a-fA-F]{2}) ([0-9a-fA-F]{2}) ([0-9a-fA-F]{2})$"), # 11 match stream
            re.compile("^.*output\.c:[\d]+: Port ([0-9a-fA-F]+), type ([\d]+), size ([\d]+)$"),                     # 12 match port
            re.compile("^.*main\.c:[\d]+: XHDR: ((?:[0-9A-Fa-f]{2} ?)+).*$"),                                 # 13 match xhdr tag
            re.compile("^.*output\.c:[\d]+: Unique file identifier: PPC;07; ([\S]+).*$")                            # 14 match unique file id
        ]`

**Comment by cmnybo** [comment]
I believe that nrcs5 changed the status messages that I used to display the info.
I intend to update nrsc5-gui to use the new python api that was recently added which will make it work again.

**Comment by argilo** [comment]
@lmore377 This should be fixed by #9.
